// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Models;
//
//    var welcome = Welcome.FromJson(jsonString);

using Newtonsoft.Json;

namespace RestAPI_Test.Models
{
    public partial class Post
    {
        [JsonProperty("userId")]
        public long UserId { get; set; }

        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("body")]
        public string Body { get; set; }
    }

    public partial class Post
    {
        public static List<Post> FromJson(string json) => JsonConvert.DeserializeObject<List<Post>>(json, Models.Converter.Settings);
    }

    public static class SerializePosts
    {
        public static string ToJson(this List<Post> self) => JsonConvert.SerializeObject(self, Models.Converter.Settings);
    }
}
