// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Models;
//
//    var welcome = Welcome.FromJson(jsonString);

using Newtonsoft.Json;

namespace Models
{
    public partial class Todo
    {
        [JsonProperty("userId")]
        public long UserId { get; set; }

        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("completed")]
        public bool Completed { get; set; }
    }

    public partial class Todo
    {
        public static List<Todo> FromJson(string json) => JsonConvert.DeserializeObject<List<Todo>>(json, Converter.Settings);
    }

    public static class SerializeTodos
    {
        public static string ToJson(this List<Todo> self) => JsonConvert.SerializeObject(self, Converter.Settings);
    }
}
